// Code generated by protoc-gen-go from "gocon.proto"
// DO NOT EDIT!

package gocon


type Header struct {
	Type	*int32	"PB(varint,1,req,name=type)"
	Port	*int32	"PB(varint,2,req,name=port)"
	XXX_unrecognized	[]byte
}
func (this *Header) Reset() {
	*this = Header{}
}
func NewHeader() *Header {
	return new(Header)
}

type AcceptBool struct {
	Accept	*bool	"PB(varint,1,req,name=accept)"
	XXX_unrecognized	[]byte
}
func (this *AcceptBool) Reset() {
	*this = AcceptBool{}
}
func NewAcceptBool() *AcceptBool {
	return new(AcceptBool)
}

func init() {
}
