// Code generated by protoc-gen-go from "header.proto"
// DO NOT EDIT!

package gocon


type Header struct {
	Size	*int32	"PB(varint,1,req,name=size)"
	Type	*int32	"PB(varint,2,req,name=type)"
	Handler	*string	"PB(bytes,3,opt,name=handler)"
	XXX_unrecognized	[]byte
}
func (this *Header) Reset() {
	*this = Header{}
}
func NewHeader() *Header {
	return new(Header)
}

func init() {
}
